{
 "title": "Windows - SQL - DB Prometheus",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "_host", "label": "host", "query": "label_values(collector)" }
  ]
 },
 "panels": [
  {
   "title": "cpu percent time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_cpu_percent_cpu_time{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "cpu pct"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "win_wmi_uptime_SystemUpTime{sonar_agent=~\"[[_host]]\"}"
    }
   ]
  },
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "win_wmi_memory_installed_kb_TotalVisibleMemorySize{sonar_agent=~\"[[_host]]\"} - ignoring(alias,host) win_perfmon_memory_available_available_kbytes{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "memory_used"
    },
    {
     "expr": "win_wmi_memory_installed_kb_TotalVisibleMemorySize{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "memory_total"
    }
   ]
  },
  {
   "title": "processor queue aka load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_processor_queue_processor_queue_aka_load{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "queue length"
    }
   ]
  },
  {
   "title": "Page File Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_page_file_usage{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "page file used"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_wmi_disk_size_Size{sonar_agent=~\"[[_host]]\"} - win_wmi_disk_size_FreeSpace{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "{{ Name }} "
    }
   ]
  },
  {
   "title": "Disk C: Average Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_disk_c_avg_queue_length{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "Queue Length"
    }
   ]
  },
  {
   "title": "Disk E: Average Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_disk_e_avg_queue_length{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "Queue Length"
    }
   ]
  },
  {
   "title": "Disk C: Reads/Writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_disk_c_read_bytes_per_second{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "Reads"
    },
    {
     "expr": "win_perfmon_disk_c_write_bytes_per_second{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Disk E: Reads/Writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_disk_e_read_bytes_per_second{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "Reads"
    },
    {
     "expr": "win_perfmon_disk_e_write_bytes_per_second{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "TCP Segments Retransmitted Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_tcp_segmemts_retransmitted_per_sec{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "segments per sec"
    }
   ]
  },
  {
   "title": "SQL Server - Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_memory_used{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "win_perfmon_sql_server_memory_committed_unused{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "Committed Unused"
    }
   ]
  },
  {
   "title": "SQL Server - Data Files Size - All",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_data_files_all_kb{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "kb"
    }
   ]
  },
  {
   "title": "SQL Server - Database Pages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_database_pages_pages{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "Pages Used"
    }
   ]
  },
  {
   "title": "SQL Server - User Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_user_connections_cxns{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "SQL Server - Network IO Waits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_network_io_waits_waits{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "Waits"
    }
   ]
  },
  {
   "title": "SQL Server - Active Parallel Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_active_parallel_threads_threads{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "SQL Server - Longest Block",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_longest_block_minutes{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "Minutes"
    }
   ]
  },
  {
   "title": "SQL Server - Longest Query Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "expr": "win_perfmon_sql_server_longest_query_time_minutes{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "Minutes",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SQL Server - Baseline Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_baseline_duration_last_run_minutes{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "Minutes"
    }
   ]
  },
  {
   "title": "SQL Server - TempDB Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_tempdb_usage_usage{sonar_agent=~\"[[_host]]\"}",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "SQL Server - Days since last backup",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "win_perfmon_sql_server_days_since_last_backup_days{sonar_agent=~\"[[_host]]\"}"
    }
   ]
  }
 ]
}